### PR TITLE
Adds new man pages for mrmsay and mrmd

### PR DESCRIPTION
**Pull request by ana-cc**

### CODE REVIEW

**Comment by janeappleseed** [comment]
Hey, thanks for the PR. Sorry for the late response — the project was abandoned and I wasn't monitoring it.

This is a good start, though I'm not satisfied with every detail. With some tweaks it could be merged, but I'm too lazy to spend time on an abandoned project.

The more important question, though, is who are you (no offense) and how did you find out about this project in the first place? 😱 (I suppose you recognize the satirical nature of this project?)

**Comment by ana-cc** [comment]
Hey,

If you let me know what things need fixing, I'll be happy to tweak them
to your satisfaction (yay groff!!).

 I'm a random person who likes ASCII art and cool GitHub tshirts.
 GitHub ran Hacktoberfest (open 4 pull requests in the month of October, 
 get a free tshirt and  stickers) and I only remembered this really
 late. Already had 2 done that month so I looked for  quick things to
 open 2 more pull requests on. I believe 'needs man' was the search
 term. This one made me laugh, and I'm quite the fan of cowsay, hence
 why I chose it. Manpage writing is something I do a lot when packaging
 things in Debian.

Hope this helps :)



On Mon, Dec 12, 2016, at 04:45 AM, Jane Appleseed wrote:

> Hey, thanks for the PR. Sorry for the late response — the project was
> abandoned and I wasn't monitoring it.
> This is a good start, though I'm not satisfied with every detail. With
> some tweaks it could be merged, but I'm too lazy to spend time on an
> abandoned project.
> The more important question, though, is who are you (no offense) and
> how did you find out about this project in the first place? 😱 (I
> suppose you recognize the satirical nature of this project?)
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/janeappleseed/MrMsay/pull/3#issuecomment-266342339

**Comment by janeappleseed** [comment]
> I'm a random person who likes ASCII art and cool GitHub tshirts.
 GitHub ran Hacktoberfest (open 4 pull requests in the month of October,
 get a free tshirt and  stickers) and I only remembered this really
 late. Already had 2 done that month so I looked for  quick things to
 open 2 more pull requests on. I believe 'needs man' was the search
 term. This one made me laugh, and I'm quite the fan of cowsay, hence
 why I chose it. Manpage writing is something I do a lot when packaging
 things in Debian.

Phew, thought my secret account and corner have been compromised. This account and repo should have been known to only two people (certainly not including the "MrM"). Apparently I underestimated discoverability on GitHub.

Regarding this PR, I think it doesn't affect your Hacktoberfest result? Documentation is quite a personal thing and after thinking it through I concluded that it would take quite some effort on my part to clarify and polish everything, something I don't want to spend on an abandoned project. Sorry, and have a nice holiday season.

**Comment by ana-cc** [comment]
The secret is safe with me.  I've already completed Hacktoberfest.
 Apologies for any undue worrying, and have a great holiday!
On Thu, Dec 15, 2016, at 05:13 AM, Jane Appleseed wrote:

>> I'm a random person who likes ASCII art and cool GitHub tshirts.

>>  GitHub ran Hacktoberfest (open 4 pull requests in the month of
>>  October,
>>  get a free tshirt and  stickers) and I only remembered this really

>>  late. Already had 2 done that month so I looked for  quick things to
>>  open 2 more pull requests on. I believe 'needs man' was the search

>>  term. This one made me laugh, and I'm quite the fan of cowsay, hence
>>  why I chose it. Manpage writing is something I do a lot when
>>  packaging
>>  things in Debian.



> Phew, thought my secret account and corner have been compromised. This
> account and repo should have been known to only two people (certainly
> not including the "MrM"). Apparently I underestimated discoverability
> on GitHub.
> Regarding this PR, I think it doesn't affect your Hacktoberfest
> result? Documentation is quite a personal thing and after thinking it
> through I concluded that it would take quite some effort on my part to
> clarify and polish everything, something I don't want to spend on an
> abandoned project. Sorry, and have a nice holiday season.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/janeappleseed/MrMsay/pull/3#issuecomment-267240797

**Pull request closed without merging**
